# Generated by Django 4.2.5 on 2023-09-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandboxaccess',
            options={'ordering': ('provider_name',)},
        ),
    ]
